[package]
name = "ThiefFMTranslationAgent"
version = "1.0.0"
edition = "2021"

[dependencies]
aes-gcm = "0.11.0-pre.2"
base64 = "0.22.1"
dirs = "5.0.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
winreg = "0.53"
sha2 = "0.11.0-pre.4"
rand = "0.9.0-beta.1"