name: Build and Release on Windows

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Package
        run: |
          mkdir release
          copy target\release\ThiefFMTranslationAgent.exe release\

      - name: Read CHANGELOG
        id: changelog
        shell: pwsh
        run: |
          $content = Get-Content CHANGELOG.md -Raw
          $content = $content -replace "`r`n","\n"
          "CHANGELOG_CONTENT=$content" >> $env:GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.CHANGELOG_CONTENT }}
          files: |
            release/ThiefFMTranslationAgent.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
